version: '3.7'
services:
  cloudy-dev:
    container_name: cloudy
    build:
      context: ./app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true